project_name: docker-loginex
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: docker-loginex
    ldflags:
      - -s -w
      - -X github.com/msfukui/docker-loginex/cmd.revision={{.ShortCommit}}
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
      arm64: arm64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
